const api = '/api'

export const ApiLogin = api+'/auth/login'
export const ApiRegister = api+'/auth/register'
export const ApiJWTRefresh = api+'/auth/refresh'
export const ApiLogout = api+'/auth/logout'
export const ApiUser = api+'/auth/user'
export const ApiCars = api+'/cars'
export const ApiCarFind = api+'/cars/find'
export const ApiEquipments = api+'/equipments'
export const ApiComments = api+'/comments'
export const ApiRating = api+'/cars/rating'
export const ApiFavorites = api+'/favorites'
export const ApiRservation = api+'/reservation'